base_url = "/"
default_language = "bg"

minify_html = true
generate_feeds = true
compile_sass = true

taxonomies = [
    { name = "type", feed = true},
    { name = "artist", feed = true},
    { name = "album", feed = true},
    { name = "director", feed = true},
    { name = "release-year", feed = true},
]

[languages.en]
generate_feeds = true

[markdown]
highlight_code = true
highlight_theme = "ayu-light"

[extra]
favicon_url = "/favicon.png"
